#!/bin/bash

# set variables
root=`whoami`
device=tapipop
pid_file=/var/run/dhclient.$device.pid
user=$(ls -l SocialVPN.exe | awk '{ print $3 }')

if [[ $root != root ]]; then
  echo "Please run as root"
  exit 1
fi

/usr/sbin/tunctl -d $device
/usr/sbin/tunctl -u $user -t $device
chmod 666 /dev/net/tun
su $user -c "/usr/bin/mono SocialVPN.exe &> log.txt &"

sleep 3

if [[ -f $pid_file ]]; then
  /bin/kill $(cat $pid_file)
fi

/sbin/dhclient -1 -pf $pid_file -lf /var/lib/dhcp3/dhclient.$device.leases $device

echo "Point your browser to http://127.0.0.1:58888"
